//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KLTN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountNhanVien
    {
        public string Account { get; set; }
        public string Password { get; set; }
        public string Ten_NhanVien { get; set; }
        public string Sdt { get; set; }
        public string Cmnd { get; set; }
        public string TrangThai { get; set; }
        public Nullable<bool> Is_Admin { get; set; }
    }
}
