//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KLTN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BangGia_Db
    {
        public int Id_BangGia { get; set; }
        public Nullable<int> Id_LoaiSan { get; set; }
        public string Ten_LoaiSan { get; set; }
        public string TrangThai_BangGia { get; set; }
        public Nullable<decimal> GiaTien { get; set; }
        public string ThoiGianBatDau { get; set; }
        public string ThoiGianKetThuc { get; set; }
        public string NgayTao { get; set; }
    }
}
