//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KLTN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CurrentUser_Db
    {
        public int Id_CurrentUser { get; set; }
        public string Account { get; set; }
        public string Password { get; set; }
        public string Sdt { get; set; }
        public string Cmnd { get; set; }
        public string HoVaTen { get; set; }
        public string TrangThai_Account { get; set; }
        public Nullable<bool> IsAdmin { get; set; }
    }
}
