//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KLTN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DanhSachHienTai_NuocUong_Db
    {
        public int Id_DanhSachHienTai { get; set; }
        public Nullable<int> Id_San { get; set; }
        public Nullable<int> Id_NuocUong { get; set; }
        public string Ten_NuocUong { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<decimal> GiaTien { get; set; }
    }
}
