//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KLTN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DanhSachNuocUongVsHoatdongHienTai
    {
        public int Index { get; set; }
        public Nullable<int> Id_DanhSachNuocUongVsHoatdongHienTai { get; set; }
        public Nullable<int> Id_SanPham { get; set; }
        public string Ten_SanPham { get; set; }
        public Nullable<decimal> Gia_SanPham { get; set; }
        public Nullable<int> SoLuong_SanPham { get; set; }
        public Nullable<decimal> TongTien { get; set; }
    }
}
