//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KLTN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoatDongHienTai_Db
    {
        public int Id_San { get; set; }
        public string Ten_San { get; set; }
        public Nullable<int> Id_LoaiSan { get; set; }
        public string Ten_LoaiSan { get; set; }
        public string GioVaoSan { get; set; }
        public string GioRaSan { get; set; }
        public Nullable<decimal> TongTien { get; set; }
        public Nullable<decimal> TienKhachDua { get; set; }
        public Nullable<decimal> TienThua { get; set; }
        public Nullable<double> SoGioThue { get; set; }
        public string NgayThucHien { get; set; }
        public string GhiChu { get; set; }
        public string Account_NhanVien { get; set; }
        public string HoVaTen_NhanVien { get; set; }
        public string TrangThai_San_HienTai { get; set; }
        public Nullable<int> Id_KhachHang { get; set; }
        public string Ten_KhachHang { get; set; }
        public string Sdt_KhachHang { get; set; }
    }
}
