//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KLTN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KhachHang
    {
        public int Id_KhachHang { get; set; }
        public string Ten_KhachHang { get; set; }
        public string Sdt_KhachTrang { get; set; }
        public string TrangThai { get; set; }
    }
}
