//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KLTN.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KLTN_DatabaseEntities : DbContext
    {
        public KLTN_DatabaseEntities()
            : base("name=KLTN_DatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Account_Db> Account_Db { get; set; }
        public virtual DbSet<BangGia_Db> BangGia_Db { get; set; }
        public virtual DbSet<CurrentUser_Db> CurrentUser_Db { get; set; }
        public virtual DbSet<DanhSachHienTai_NuocUong_Db> DanhSachHienTai_NuocUong_Db { get; set; }
        public virtual DbSet<DanhSachHoaDon_NuocUong_Db> DanhSachHoaDon_NuocUong_Db { get; set; }
        public virtual DbSet<HoaDon_Db> HoaDon_Db { get; set; }
        public virtual DbSet<HoatDongHienTai_Db> HoatDongHienTai_Db { get; set; }
        public virtual DbSet<KhachHang_Db> KhachHang_Db { get; set; }
        public virtual DbSet<LichDat_Db> LichDat_Db { get; set; }
        public virtual DbSet<LoaiSan_Db> LoaiSan_Db { get; set; }
        public virtual DbSet<NuocUong_Db> NuocUong_Db { get; set; }
        public virtual DbSet<San_Db> San_Db { get; set; }
        public virtual DbSet<PhieuThu_Db> PhieuThu_Db { get; set; }
    }
}
