//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KLTN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LichDat_NgaySuDung
    {
        public int Id { get; set; }
        public Nullable<int> Id_LichDat { get; set; }
        public string Nam { get; set; }
        public string Thang { get; set; }
        public string Ngay { get; set; }
    }
}
