//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KLTN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class San
    {
        public int Id_San { get; set; }
        public string Ten_San { get; set; }
        public string Id_LoaiSan { get; set; }
        public string Ten_LoaiSan { get; set; }
        public string TrangThai { get; set; }
    }
}
